name: moreway
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  auto_size_text: ^3.0.0
  bloc: ^8.1.3
  curl_logger_dio_interceptor: ^1.0.0
  dio: ^5.4.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_native_splash: ^2.3.10
  flutter_screenutil: ^5.9.0
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^2.0.10+1
  geocoding: ^3.0.0
  geolocator: ^11.0.0
  get_it: ^7.6.7
  go_router: ^13.2.0
  google_maps_flutter: ^2.5.3
  injectable: ^2.3.5
  json_annotation: ^4.8.1
  meta: ^1.10.0
  

dev_dependencies:
  flutter_launcher_icons: "^0.13.1"
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  mockito: ^5.4.4
  injectable_generator: ^2.4.2 

flutter:
  uses-material-design: true
  assets:
    - assets/icons/home_icon.svg
    - assets/icons/home_icon.png
    - assets/images/welcome.jpg
    - assets/images/logo.png
    - assets/images/logo1152.png
    - assets/images/logo400.png
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 500