name: moreway
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  bloc: ^8.1.3
  dio: ^5.4.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_native_splash: ^2.3.10
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^2.0.10+1
  geolocator: ^11.0.0
  get_it: ^7.6.7
  go_router: ^13.2.0
  json_annotation: ^4.8.1
  meta: ^1.10.0
  shared_preferences: ^2.2.2
  modal_bottom_sheet:
    git:
      url: https://github.com/followthemoney1/modal_bottom_sheet.git
      ref: main
      path: modal_bottom_sheet
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  flutter_rating_bar: ^4.0.1
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0
  syncfusion_flutter_sliders: ^25.1.41
  readmore: ^3.0.0
  intl: ^0.19.0

dev_dependencies:
  flutter_launcher_icons: "^0.13.1"
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/icons/home_icon.svg
    - assets/icons/home_icon.png
    - assets/images/welcome.jpg
    - assets/images/logo.png
    - assets/images/logo1152.png
    - assets/images/logo400.png
    - assets/images/error.jpg
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 500